[package]
name = "kafka"
version = "0.8.0"
authors = ["Yousuf Fauzan", "Petr Novotnik <pnovotnik@googlemail.com>"]
description = "Rust client for Apache Kafka"
homepage = "https://github.com/kafka-rust/kafka-rust"
repository = "https://github.com/kafka-rust/kafka-rust"
keywords = ["kafka", "queue"]
license = "MIT"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
crc = "2.1.0"
ref_slice = "1.2.1"
fnv = "1.0.7"
twox-hash = "1.6.2"

flate2 = { version = "1.0.22", optional = true }
snap = { version = "1.0.5", optional = true }
openssl = { version = "0.10.38", optional = true }
openssl-sys = { version = "0.9.72", optional = true }
thiserror = "1.0.30"
tracing = "0.1.31"

[dev-dependencies]
getopts = "0.2.21"
env_logger = "0.9.0"
time = "0.3.7"
rand = "0.8.5"
lazy_static = "1.4.0"
anyhow = "1.0.55"


[features]
default = ["snappy", "gzip", "security"]
snappy = ["snap"]
gzip = ["flate2"]
security = ["openssl", "openssl-sys"]
nightly = []
integration_tests = []
